Add a test plan covering kvs functionality
refenv/cijoe-pkg-xnvme pull request #1
Opened 2022-03-07 09:02 UTC by halfzebra

The test covers the identification of KV namespace, enumeration of KV namespaces,
retrieve, exist, list commands and a basic I/O test

Signed-off-by: Eduard Kyvenko <e.kyvenko@samsung.com>

2022-03-11 08:11 UTC, safl requested changes
This is looking really good, thanks!
Couple of comments inline.

2022-03-11 08:11 UTC, safl commented on testcases/xnvme_kvs_exist.sh
> +cij.cmd "kvs delete ${XNVME_URI} ${XNVME_RT_ARGS} --key ${KV_KEY}"
This is needing some error-handling?

2022-03-11 08:11 UTC, safl commented on testcases/xnvme_kvs_retrieve.sh
> +cij.cmd "kvs delete ${XNVME_URI} ${XNVME_RT_ARGS} --key ${KV_KEY}"
Same here, why no error-handling?

2022-03-11 08:11 UTC, safl commented on testcases/xnvme_kvs_list.sh
> +cij.cmd "kvs delete ${XNVME_URI} ${XNVME_RT_ARGS} --key ${KV_KEY_FROM}"
And here?

2022-03-11 08:11 UTC, safl commented on testplans/xnvme-kvs-spdk.plan
> +  CMD_PREFIX: " "
This should also work on Linux via NVMe driver-ioctl(), so it would be good with testplans testing those paths as well.
Like adding:
``xnvme-kvs-linux-.plan``
Invoking the same testsuites, but using:
```
XNVME_BE: "linux"
```

2022-03-11 08:11 UTC, safl commented on testcases/xnvme_kvs_exist.sh
> +cij.cmd "kvs delete ${XNVME_URI} ${XNVME_RT_ARGS} --key ${KV_KEY}"
I guess it is done to ensure a certain device-state.
But then, instead just use ``cij.info`` and output and informational message, but still wrap the command with ``if ..; then``

2022-03-11 11:49 UTC, halfzebra commented on testcases/xnvme_kvs_exist.sh
> +cij.cmd "kvs delete ${XNVME_URI} ${XNVME_RT_ARGS} --key ${KV_KEY}"
Good point, the absence of error handling actually makes those tests dependent on drive state.

2022-03-11 11:53 UTC, halfzebra commented on testplans/xnvme-kvs-spdk.plan
> +  CMD_PREFIX: " "
Would this work with a block device?

2022-03-14 08:50 UTC, safl commented on testplans/xnvme-kvs-spdk.plan
> +  CMD_PREFIX: " "
Would not work with a block-device, but will work with the generic-ns-char-device e.g. typically named ``/dev/ng0n1``.

2022-03-14 14:08 UTC, safl commented on testplans/xnvme-kvs-linux.plan
> +  DEV_TYPE: "nvme"
this looks weird

2022-03-17 12:00 UTC, safl approved these changes
Excellent, thank you.

2022-03-17 12:00 UTC, merged